/**
 * DriverProfiles - 16 curated drivers across 4 multi-class categories (GTP, LMP2, GT3, GT4)
 */

export const MULTI_CLASS_CONFIG = {
  GTP: {
    className: 'GTP',
    color: 0xff3b30, // Red
    colorHex: '#ff3b30',
    speedModifier: 1.15, // Fastest (~315 km/h)
    baseLapTime: 120.5,  // ~2:00.5 at Spa
  },
  LMP2: {
    className: 'LMP2',
    color: 0x007aff, // Blue
    colorHex: '#007aff',
    speedModifier: 1.08, // (~295 km/h)
    baseLapTime: 125.0,  // ~2:05.0 at Spa
  },
  GT3: {
    className: 'GT3',
    color: 0x34c759, // Green
    colorHex: '#34c759',
    speedModifier: 1.00, // (~270 km/h)
    baseLapTime: 136.5,  // ~2:16.5 at Spa
  },
  GT4: {
    className: 'GT4',
    color: 0xff9500, // Orange
    colorHex: '#ff9500',
    speedModifier: 0.91, // (~245 km/h)
    baseLapTime: 148.0,  // ~2:28.0 at Spa
  },
};

export const DEFAULT_DRIVERS = [
  // --- GTP CLASS (4 cars) ---
  {
    CarIdx: 1,
    UserName: "Max Verstappen",
    CarNumber: "1",
    CarClassShortName: "GTP",
    CarClassColor: MULTI_CLASS_CONFIG.GTP.color,
    CarScreenNameShort: "Cadillac V-Series.R",
    IRating: 7800,
    SR: 4.9,
    LicLevel: 4,
    LicString: "A 4.9",
    isPlayer: false,
    initialGridPosition: 1,
    initialLapDistPct: 0.035,
    speedVariance: 1.015,
  },
  {
    CarIdx: 2,
    UserName: "Lewis Hamilton",
    CarNumber: "44",
    CarClassShortName: "GTP",
    CarClassColor: MULTI_CLASS_CONFIG.GTP.color,
    CarScreenNameShort: "Porsche 963 GTP",
    IRating: 7400,
    SR: 4.8,
    LicLevel: 4,
    LicString: "A 4.8",
    isPlayer: false,
    initialGridPosition: 2,
    initialLapDistPct: 0.030,
    speedVariance: 1.010,
  },
  {
    CarIdx: 3,
    UserName: "Charles Leclerc",
    CarNumber: "16",
    CarClassShortName: "GTP",
    CarClassColor: MULTI_CLASS_CONFIG.GTP.color,
    CarScreenNameShort: "BMW M Hybrid V8",
    IRating: 6900,
    SR: 4.2,
    LicLevel: 4,
    LicString: "A 4.2",
    isPlayer: false,
    initialGridPosition: 3,
    initialLapDistPct: 0.026,
    speedVariance: 1.008,
  },
  {
    CarIdx: 4,
    UserName: "Lando Norris",
    CarNumber: "4",
    CarClassShortName: "GTP",
    CarClassColor: MULTI_CLASS_CONFIG.GTP.color,
    CarScreenNameShort: "Acura ARX-06",
    IRating: 6700,
    SR: 3.9,
    LicLevel: 4,
    LicString: "A 3.9",
    isPlayer: false,
    initialGridPosition: 4,
    initialLapDistPct: 0.022,
    speedVariance: 1.004,
  },

  // --- LMP2 CLASS (4 cars) ---
  {
    CarIdx: 5,
    UserName: "Fernando Alonso",
    CarNumber: "14",
    CarClassShortName: "LMP2",
    CarClassColor: MULTI_CLASS_CONFIG.LMP2.color,
    CarScreenNameShort: "Dallara P217 LMP2",
    IRating: 6500,
    SR: 4.7,
    LicLevel: 4,
    LicString: "A 4.7",
    isPlayer: false,
    initialGridPosition: 5,
    initialLapDistPct: 0.018,
    speedVariance: 1.006,
  },
  {
    CarIdx: 6,
    UserName: "Oscar Piastri",
    CarNumber: "81",
    CarClassShortName: "LMP2",
    CarClassColor: MULTI_CLASS_CONFIG.LMP2.color,
    CarScreenNameShort: "Dallara P217 LMP2",
    IRating: 5800,
    SR: 3.8,
    LicLevel: 3,
    LicString: "B 3.8",
    isPlayer: false,
    initialGridPosition: 6,
    initialLapDistPct: 0.014,
    speedVariance: 1.002,
  },
  {
    CarIdx: 7,
    UserName: "George Russell",
    CarNumber: "63",
    CarClassShortName: "LMP2",
    CarClassColor: MULTI_CLASS_CONFIG.LMP2.color,
    CarScreenNameShort: "Dallara P217 LMP2",
    IRating: 5400,
    SR: 3.6,
    LicLevel: 3,
    LicString: "B 3.6",
    isPlayer: false,
    initialGridPosition: 7,
    initialLapDistPct: 0.010,
    speedVariance: 0.998,
  },
  {
    CarIdx: 8,
    UserName: "Carlos Sainz",
    CarNumber: "55",
    CarClassShortName: "LMP2",
    CarClassColor: MULTI_CLASS_CONFIG.LMP2.color,
    CarScreenNameShort: "Dallara P217 LMP2",
    IRating: 5100,
    SR: 3.5,
    LicLevel: 3,
    LicString: "B 3.5",
    isPlayer: false,
    initialGridPosition: 8,
    initialLapDistPct: 0.007,
    speedVariance: 0.996,
  },

  // --- GT3 CLASS (4 cars - Player is CarIdx: 9) ---
  {
    CarIdx: 9,
    UserName: "Player (You)",
    CarNumber: "77",
    CarClassShortName: "GT3",
    CarClassColor: MULTI_CLASS_CONFIG.GT3.color,
    CarScreenNameShort: "Porsche 911 GT3 R (992)",
    IRating: 4500,
    SR: 4.1,
    LicLevel: 4,
    LicString: "A 4.1",
    isPlayer: true,
    initialGridPosition: 9,
    initialLapDistPct: 0.004,
    speedVariance: 1.000,
  },
  {
    CarIdx: 10,
    UserName: "Yuki Tsunoda 角田 裕毅",
    CarNumber: "22",
    CarClassShortName: "GT3",
    CarClassColor: MULTI_CLASS_CONFIG.GT3.color,
    CarScreenNameShort: "Ferrari 296 GT3",
    IRating: 4200,
    SR: 3.2,
    LicLevel: 3,
    LicString: "B 3.2",
    isPlayer: false,
    initialGridPosition: 10,
    initialLapDistPct: 0.002,
    speedVariance: 1.002,
  },
  {
    CarIdx: 11,
    UserName: "Zhou Guanyu 周冠宇",
    CarNumber: "24",
    CarClassShortName: "GT3",
    CarClassColor: MULTI_CLASS_CONFIG.GT3.color,
    CarScreenNameShort: "BMW M4 GT3",
    IRating: 3600,
    SR: 2.9,
    LicLevel: 2,
    LicString: "C 2.9",
    isPlayer: false,
    initialGridPosition: 11,
    initialLapDistPct: 0.000,
    speedVariance: 0.995,
  },
  {
    CarIdx: 12,
    UserName: "Alex Albon",
    CarNumber: "23",
    CarClassShortName: "GT3",
    CarClassColor: MULTI_CLASS_CONFIG.GT3.color,
    CarScreenNameShort: "Mercedes-AMG GT3 Evo",
    IRating: 3900,
    SR: 3.4,
    LicLevel: 3,
    LicString: "B 3.4",
    isPlayer: false,
    initialGridPosition: 12,
    initialLapDistPct: 0.998,
    speedVariance: 0.997,
  },

  // --- GT4 CLASS (4 cars) ---
  {
    CarIdx: 13,
    UserName: "Алексей Смирнов",
    CarNumber: "17",
    CarClassShortName: "GT4",
    CarClassColor: MULTI_CLASS_CONFIG.GT4.color,
    CarScreenNameShort: "Aston Martin Vantage GT4",
    IRating: 2800,
    SR: 2.7,
    LicLevel: 2,
    LicString: "C 2.7",
    isPlayer: false,
    initialGridPosition: 13,
    initialLapDistPct: 0.995,
    speedVariance: 1.004,
  },
  {
    CarIdx: 14,
    UserName: "Pierre Gasly",
    CarNumber: "10",
    CarClassShortName: "GT4",
    CarClassColor: MULTI_CLASS_CONFIG.GT4.color,
    CarScreenNameShort: "McLaren Artura GT4",
    IRating: 2600,
    SR: 3.0,
    LicLevel: 2,
    LicString: "C 3.0",
    isPlayer: false,
    initialGridPosition: 14,
    initialLapDistPct: 0.992,
    speedVariance: 1.000,
  },
  {
    CarIdx: 15,
    UserName: "Esteban Ocon",
    CarNumber: "31",
    CarClassShortName: "GT4",
    CarClassColor: MULTI_CLASS_CONFIG.GT4.color,
    CarScreenNameShort: "BMW M4 GT4",
    IRating: 2400,
    SR: 2.4,
    LicLevel: 1,
    LicString: "D 2.4",
    isPlayer: false,
    initialGridPosition: 15,
    initialLapDistPct: 0.989,
    speedVariance: 0.993,
  },
  {
    CarIdx: 16,
    UserName: "Nico Hulkenberg",
    CarNumber: "27",
    CarClassShortName: "GT4",
    CarClassColor: MULTI_CLASS_CONFIG.GT4.color,
    CarScreenNameShort: "Porsche 718 Cayman GT4",
    IRating: 2200,
    SR: 2.1,
    LicLevel: 1,
    LicString: "D 2.1",
    isPlayer: false,
    initialGridPosition: 16,
    initialLapDistPct: 0.986,
    speedVariance: 0.990,
  }
];
